{% set name = "Genesis-PyAPI" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2989f582eb619cd18c0fda10c69d38404781ddc4161a77f18c29d02fbdee577c

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - requests  >=2.6.0
    - slumber   >=0.7.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - genesis

about:
  home: https://github.com/genialis/genesis-pyapi
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: "Python API for the Genesis platform."

  description: |
    Python API for the Genesis platform.
  doc_url: ""
  dev_url: https://github.com/genialis/genesis-pyapi

extra:
  recipe-maintainers:
    - jakakokosar
    - astaric
