travis:
  secure:
    BINSTAR_TOKEN: k+JOEiuIC2u9gCCLqtQMaSY5hHWL64kUhxVVeuDP0kZhIVV+TGi13qSyI2y7PLtODamj6bSIlQL0JK/5RkGSn/A4MpVrq8Fliz7bHSz/mYFueZWwSfnSsJaYpEm65W9Qny6MYCRXVeTQgh2HfcqL1fgs3JTaiapK7cjdLRH9BqrW4HzP2MX+eWqscP+MjxRny55dEJiQTTbi+D9mhC6j+M+Mvzk2afU1Dx22gX/84sYZQ6Ri+0x+MRYmUkXnaxaylXzWM42iYm3Qs+piSI9PXwa/XCmDUUj1UTdVgu7TECFSZr4tzFDhY2PGKoGChVmknqx4Ny4bzUIQ1d6eutv4+r8thisILIoF5gEDvGzWmUNLvuCheC0Fa5jtrRwE/klMpgtP4do8vMTYXBfGXkZTNoLfwhi+1F+b6iZ0Llj/2MHPzrBYbYIMyU+97l48b50AhBfRw634eVRyByUTTzMMfkfv+Odwcdq8Xz5+skU+aF4HdCnjak+YKqpBrro3Pmu0zNysnKJfUxFjNJCADJiMOakUPksEVsHl+9wzdOGAvB1q4TcFLIS4V2K5kv/SxBNyDv+rDr1l2+AnaBmi/Nb0+4Z9D4pX+G7JIu7meNJWKQI8FpQEK/g5I1AGBSrIq6yLjhyWUkEKg4myG3LB08SK+pACcKnw1GKGuZiIxLrcPCc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
